
mirror_api:
    resource: "@MirrorApiBundle/Controller/"
    type:     annotation
    prefix:   /api

mirror_adm:
    resource: "@MirrorWebBundle/Controller/"
    type:     annotation
    prefix:   /web

mirror_index:
    pattern:  /
    defaults: { _controller: MirrorWebBundle:Login:index }
