AdminRole:
    type: entity
    table: admin_role
    indexes:
        adminId:
            columns:
                - admin_id
        roleId:
            columns:
                - role_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        adminId:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: admin_id
        roleId:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: role_id
        createTime:
            type: datetime
            nullable: false
            column: create_time
        updateTime:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
            column: update_time
    lifecycleCallbacks: {  }
