CallTraces:
    type: entity
    table: call_traces
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        api:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        session:
            type: text
            nullable: false
            length: null
            options:
                fixed: false
        request:
            type: text
            nullable: false
            length: null
            options:
                fixed: false
        response:
            type: text
            nullable: false
            length: null
            options:
                fixed: false
        status:
            type: integer
            nullable: false
            options:
                unsigned: false
        createTime:
            type: datetime
            nullable: false
            column: create_time
        updateTime:
            type: datetime
            nullable: false
            column: update_time
    lifecycleCallbacks: {  }
