Company:
    type: entity
    table: company
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
                comment: 企业ID
            id: true
            generator:
                strategy: IDENTITY
    fields:
        companyType:
            type: string
            nullable: false
            length: 32
            options:
                fixed: false
                comment: 公司业务类型
                default: '0'
            column: company_type
        companyName:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
                comment: 公司名字
                default: ''
            column: company_name
        certificateType:
            type: string
            nullable: false
            length: 32
            options:
                fixed: false
                comment: 证件类型
                default: '0'
            column: certificate_type
        socialCreditCode:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
                comment: 社会信用代码
                default: ''
            column: social_credit_code
        certificatePhoto:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
                comment: 多合一营业执照
                default: ''
            column: certificate_photo
        legalPersonName:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
                comment: 法人代表姓名
                default: ''
            column: legal_person_name
        legalPersonId:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
                comment: 法人代码姓名
                default: ''
            column: legal_person_id
        legalPersonIdPhoto:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
                comment: 法人代表身份证号
                default: ''
            column: legal_person_id_photo
        accountOpeningLicense:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
                comment: 开户许可证
                default: ''
            column: account_opening_license
        accountOpeningLicensePhoto:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
                comment: 开户许可证核准号
                default: ''
            column: account_opening_license_photo
        refuseMessage:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
                default: ''
            column: refuse_message
        sort:
            type: integer
            nullable: false
            options:
                unsigned: false
                default: '0'
        province:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        city:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        type:
            type: integer
            nullable: false
            options:
                unsigned: false
                comment: '1:催收公司  2:代理商'
        status:
            type: integer
            nullable: false
            options:
                unsigned: false
                default: '0'
        createTime:
            type: datetime
            nullable: false
            column: create_time
        updateTime:
            type: datetime
            nullable: false
            column: update_time
    lifecycleCallbacks: {  }
