DictKey:
    type: entity
    table: dict_key
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        description:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        status:
            type: integer
            nullable: true
            options:
                unsigned: false
        createTime:
            type: datetime
            nullable: false
            column: create_time
        updateTime:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
            column: update_time
    lifecycleCallbacks: {  }
