News:
    type: entity
    table: news
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        shortDesc:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
            column: short_desc
        content:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
        source:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
                comment: 来源
        photo:
            type: integer
            nullable: false
            options:
                unsigned: false
        status:
            type: integer
            nullable: false
            options:
                unsigned: false
        createTime:
            type: datetime
            nullable: false
            column: create_time
        updateTime:
            type: datetime
            nullable: false
            options:
                default: '0000-00-00 00:00:00'
            column: update_time
    lifecycleCallbacks: {  }
