Permission:
    type: entity
    table: permission
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        value:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        desc:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        method:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        parentId:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: parent_id
        status:
            type: integer
            nullable: false
            options:
                unsigned: false
        createTime:
            type: datetime
            nullable: false
            column: create_time
        updateTime:
            type: datetime
            nullable: false
            column: update_time
    lifecycleCallbacks: {  }
