PropertyEquipment:
    type: entity
    table: property_equipment
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
                comment: 设备名称
        isTicket:
            type: integer
            nullable: false
            options:
                unsigned: false
                comment: 是否有发票
            column: is_ticket
        isPledge:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: is_pledge
        country:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        province:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        city:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        source:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        propertyId:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: property_id
        status:
            type: integer
            nullable: false
            options:
                unsigned: false
        createTime:
            type: datetime
            nullable: false
            column: create_time
        updateTime:
            type: datetime
            nullable: false
            options:
                default: '0000-00-00 00:00:00'
            column: update_time
    lifecycleCallbacks: {  }
