Suggesstion:
    type: entity
    table: suggesstion
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        content:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        name:
            type: string
            nullable: false
            length: 32
            options:
                fixed: false
        phonenumber:
            type: string
            nullable: false
            length: 32
            options:
                fixed: false
        createTime:
            type: datetime
            nullable: false
            column: create_time
        updateTime:
            type: datetime
            nullable: false
            options:
                default: '0000-00-00 00:00:00'
            column: update_time
        status:
            type: integer
            nullable: false
            options:
                unsigned: false
                default: '1'
        sort:
            type: integer
            nullable: false
            options:
                unsigned: false
                default: '0'
    lifecycleCallbacks: {  }
