UserDetail:
    type: entity
    table: user_detail
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        userId:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: user_id
        realName:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: real_name
        idCard:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: id_card
        evidencePhoto:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: evidence_photo
        status:
            type: integer
            nullable: false
            options:
                unsigned: false
        createTime:
            type: datetime
            nullable: false
            column: create_time
        updateTime:
            type: datetime
            nullable: false
            options:
                default: '0000-00-00 00:00:00'
            column: update_time
        refuseMessage:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
                default: ' '
            column: refuse_message
    lifecycleCallbacks: {  }
