User:
    type: entity
    table: user
    indexes:
        openId:
            columns:
                - openId
    uniqueConstraints:
        telephone:
            columns:
                - telephone
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        telephone:
            type: string
            nullable: false
            length: 11
            options:
                fixed: false
        openid:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
            column: openId
        status:
            type: integer
            nullable: false
            options:
                unsigned: false
        createTime:
            type: datetime
            nullable: false
            column: create_time
        updateTime:
            type: datetime
            nullable: false
            options:
                default: '''0000-00-00 00:00:00'''
            column: update_time
    lifecycleCallbacks: {  }
