parameters:
services:
    json_parse:
        class: Mirror\ApiBundle\Util\JsonParser
################################################
    base_model:
        class: Mirror\ApiBundle\Model\BaseModel
        arguments: [@validator,@doctrine.orm.entity_manager]
        abstract: true
    dbal_base_model:
        class: Mirror\ApiBundle\Model\DbalBaseModel
        arguments: [@database_connection]
        abstract: true